apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: my-app
type: Opaque
stringData:
  VAULT_ADDR: http://44.204.193.107:8200
  VAULT_ROLE_ID:                                       #Reach for role_id 
  VAULT_SECRET_ID:                                     #Reach out for secret


